import os
from typing import Any, Callable, Iterable

import geojson
import numpy as np
import yaml
from csbdeep.utils import normalize
from imageio import imread
from shapely import Point, Polygon
from stardist.models import StarDist2D


INPUT_DIR = "/inputs"
OUTPUT_DIR = "/outputs"
MODEL_DATA_DIR = "/models/"


def is_nucleus_inside_roi(
  nucleus_coords: np.ndarray,
  roi_polygon: Polygon,
  image_height: int
) -> bool:
  """
  Check if a nucleus centroid is inside the ROI polygon.

  Args:
    nucleus_coords: StarDist format (2, N) where row 0 is y, row 1 is x.
    roi_polygon: ROI polygon in (x, flipped-y) coordinate space.
    image_height: Used to flip Y into the ROI coordinate system.

  Returns:
    True if the nucleus centroid is inside the ROI, False otherwise.
  """

  centroid_x = np.mean(nucleus_coords[1])
  centroid_y = image_height - np.mean(nucleus_coords[0])

  return roi_polygon.contains(Point(centroid_x, centroid_y))


def from_stardist_to_geojson_string(stardist_polygroup: np.ndarray, image_height: int):
  """Converts a polygon coordinates ndarray generated by the stardist algorithm into a geojson string.

  Args:
    stardist_polygroup (np.ndarray): The polygon coordinates ndarray generated by the stardist algorithm.
    image_height (int): the image height.

  Returns:
    str: The geojson string representation of the polygon.
  """

  # Reverse (y,x) → (x,y)
  coordinates = np.vstack(stardist_polygroup[::-1]).transpose()

  # Flip Y coordinates for Cytomine
  coordinates[:, 1] = image_height - coordinates[:, 1]

  # Close the polygon
  coordinates = coordinates.tolist()
  coordinates.append(coordinates[0])

  return geojson.dumps(geojson.Polygon([coordinates], validate=True))


def read_parameter(path: str, cast_fn: Callable[[str], Any], default: Any=None, raise_if_missing: bool=False):
  """
  Read a parameter from a file structured following App Engine conventions.

  Args:
    path (str): The path to the parameter file.
    cast_fn (Callable[[str], Any]): A function to cast the content of the file to the desired type.
    default (Any, optional): The default value to return if the file is not found. Defaults to None.
    raise_if_missing (bool, optional): Whether to raise a FileNotFoundError if the file is not found.
      If set to False, the default value will be returned. Defaults to False.

  Returns:
    Any: The parameter value casted to the desired type.

  Raises:
    FileNotFoundError: If the file is not found and raise_if_missing is set to True.
  """
  if not os.path.isfile(path):
    if raise_if_missing:
      raise FileNotFoundError(f"could not find parameter file '{path}'")
    else:
      return default
  with open(path, "r", encoding="utf8") as file:
    content = file.read()
    return cast_fn(content)


def write_array(array_path: str, array_data: Iterable[Any], format_fn: Callable[[Any], str]):
  """
  Write an array of data to files following App Engine conventions.

  Parameters:
    array_path (str): The path to the directory where the array files will be written.
    array_data (Iterable[Any]): The array of data to be written.
    format_fn (Callable[[Any], str]): A function that formats each data item before writing them into a file.

  Returns:
    None
  """
  os.makedirs(array_path, exist_ok=True)
  # writing array metadata
  with open(os.path.join(array_path, "array.yml"), "w+", encoding="utf8") as file:
    yaml.dump({"size": len(array_data)}, file)
  # writing array data content
  for i, data_item in enumerate(array_data):
    with open(os.path.join(array_path, f"{i}"), "w+", encoding="utf8") as file:
      file.write(format_fn(data_item))


def main():
  # Read inputs
  stardist_norm_perc_low = read_parameter(os.path.join(INPUT_DIR, "stardist_norm_perc_low"), cast_fn=float, default=1.0)
  stardist_norm_perc_high = read_parameter(os.path.join(INPUT_DIR, "stardist_norm_perc_high"), cast_fn=float, default=99.0)
  stardist_prob_t = read_parameter(os.path.join(INPUT_DIR, "stardist_prob_t"), cast_fn=float, default=0.5)
  stardist_nms_t = read_parameter(os.path.join(INPUT_DIR, "stardist_nms_t"), cast_fn=float, default=0.5)
  image_dir = os.path.join(INPUT_DIR, "images")

  roi_path = os.path.join(INPUT_DIR, "image.geojson")
  roi_polygon = None
  if os.path.isfile(roi_path):
    with open(roi_path, "r") as fp:
      roi_content = fp.read().strip()
      roi = geojson.loads(roi_content)
      roi_polygon = Polygon(roi['coordinates'][0])

  # use local model file in ~/models/2D_versatile_HE/
  model = StarDist2D(None, name='2D_versatile_HE', basedir=MODEL_DATA_DIR)

  files = os.listdir(image_dir)
  files.remove("array.yaml")

  for index, filename in enumerate(files):
    # processing image
    image_raw = imread(os.path.join(INPUT_DIR, "images", filename))
    image_height = image_raw.shape[0]

    img = normalize(
      image_raw,
      stardist_norm_perc_low,
      stardist_norm_perc_high,
      axis=(0, 1)  # normalize channels independently
    )

    # Stardist model prediction with thresholds
    _, details = model.predict_instances(
      img,
      prob_thresh=stardist_prob_t,
      nms_thresh=stardist_nms_t,
      n_tiles=model._guess_n_tiles(img)
    )

    # Filter nuclei if ROI is provided
    if roi_polygon is not None:
      filtered_coords = []
      filtered_probs = []

      for i, nucleus_coords in enumerate(details["coord"]):
        if is_nucleus_inside_roi(nucleus_coords, roi_polygon, image_height):
          filtered_coords.append(nucleus_coords)
          filtered_probs.append(details["prob"][i])
    else:
      filtered_coords = list(details["coord"])
      filtered_probs = details["prob"].tolist()

    # writing outputs
    write_array(
        array_path=os.path.join(OUTPUT_DIR, "nuclei", str(index)),
        array_data=filtered_coords,
        format_fn=lambda poly: from_stardist_to_geojson_string(poly, image_height),
    )
    write_array(
        array_path=os.path.join(OUTPUT_DIR, "probs", str(index)),
        array_data=filtered_probs,
        format_fn=str,
    )

if __name__ == "__main__":
  main()
